name: Main workflow
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cask_version:
          - '0.8.0'
          - '0.8.4'
          - 'snapshot'
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 10.x

    - uses: purcell/setup-emacs@master
      with:
        version: 26.3

    - run: yarn install
    - run: yarn run format-check
    - run: yarn test

    - uses: ./
      with:
        version: ${{ matrix.cask_version }}
